apiVersion: v1
kind: Service
metadata:
  name: backend-service
spec:
  ports:
  - name: "8080"
    port: 8080
    targetPort: 8080
  selector:
    app: be
  type: NodePort
---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: be
spec:
  replicas: 1
  strategy: {}
  template:
    metadata:
      labels:
        app: be
    spec:
      containers:
      - env:
        - name: DATABASE_PASSWORD
          value: password
        - name: DATABASE_SOURCE
          value: jdbc:mysql://lab01-mysql:3306/testdb?useUnicode=yes&characterEncoding=UTF-8&useSSL=false
        - name: DATABASE_USER
          value: root
        image: prod-cluster.icp:8500/sa-labs/be:1.3
        name: be
        ports:
        - containerPort: 8080
        resources: {}
      restartPolicy: Always
status: {}
