apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: labs01-mysql-pvc
  annotations:
    volume.beta.kubernetes.io/storage-class: gluster-heketi
spec:
  storageClassName: gluster-heketi
  accessModes:
   - ReadWriteMany
  resources:
    requests:
      storage: 3Gi
---
apiVersion: v1
kind: Service
metadata:
  name: lab01-mysql
spec:
  ports:
  - name: "3306"
    port: 3306
    targetPort: 3306
  selector:
    app: lab01-mysql
---
apiVersion: apps/v1 # for versions before 1.9.0 use apps/v1beta2
kind: Deployment
metadata:
  name: lab01-mysql
spec:
  selector:
    matchLabels:
      app: lab01-mysql
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: lab01-mysql
    spec:
      containers:
      - image: mysql:5.6
        name: mysql
        env:
          # Use secret in real usage
        - name: MYSQL_ROOT_PASSWORD
          value: password
        ports:
        - containerPort: 3306
          name: mysql
        volumeMounts:
        - name: labs01-mysql-pvc
          mountPath: /var/lib/mysql
      volumes:
      - name: labs01-mysql-pvc
        persistentVolumeClaim:
          claimName: labs01-mysql-pvc
